Лабораторная работа №6
Programming-Classrooms/practicalworks-NikitaKonturov pull request #10
Opened 2023-11-26 21:23 UTC by NikitaKonturov

2023-12-07 10:51 UTC, AlexandrOsiptsov requested changes
Полный абзац. Ощущение, что этот код писали 4 человека, которые заранее не договорились о правилах оформления. За проверку я встретил: 
1. 3 типа названий функций (camelCase, PascalCase, snake_сase).
2. 3 типа названий переменных (аналогично)
3. 3 типа оформления скобок условий
4. 2 типа выбрасываемых исключений 

Увижу ещё где-то подобное отношение к коду - 0 за лабу.

2023-12-07 10:51 UTC, AlexandrOsiptsov commented on laboratory-task-6/Laba6.cpp
> +void quickSort(typeArr* array, size_t leftBoard, size_t rightBoard) {
Абстрактный тип назвал ужасно. Можно подумать, что это массив, а не элемент массива. Обычно называют просто `T`.

2023-12-07 10:51 UTC, AlexandrOsiptsov commented on laboratory-task-6/Laba6.cpp
> +template<typename TypeArr> // temlate for int, double,char
Так же история

2023-12-07 10:51 UTC, AlexandrOsiptsov commented on laboratory-task-6/Laba6.cpp
> +size_t BinareSearch(TypeArr* arr, size_t lenArr, TypeArr ell) {
Что у тебя происходит с названиями вообще? 3 разных типа названий в одном файле

2023-12-07 10:51 UTC, AlexandrOsiptsov commented on laboratory-task-6/Laba6.cpp
> +        }
Это прям плохо. Бинарный поиск можно спокойно реализовать без подобных извращений. Посмотри реализации в сети

2023-12-07 10:51 UTC, AlexandrOsiptsov commented on laboratory-task-6/Laba6.cpp
> +    }
- До этого ты выбрасывал исключения через `std::exception`
- Зачем выбрасывать исключение, если элемент не найден? Это нормальный, а не аварийный, результат поиска

2023-12-07 19:16 UTC, NikitaKonturov commented on laboratory-task-6/Laba6.cpp
> +    if (text.size() == 0) throw std::exception("File is epmty");
2d8136e66e6b76afe10210e057b1d2aa0b196ade

2023-12-07 19:21 UTC, NikitaKonturov commented on laboratory-task-6/Laba6.cpp
> +}
Делал с расчётом чтобы исключить ошибки в тех случаях когда строка может передаваться не коректно при передаче её в конструктор
2d8136e66e6b76afe10210e057b1d2aa0b196ade

2023-12-07 19:21 UTC, NikitaKonturov commented on laboratory-task-6/Laba6.cpp
> +}
2d8136e66e6b76afe10210e057b1d2aa0b196ade

2023-12-07 19:22 UTC, NikitaKonturov commented on laboratory-task-6/Laba6.cpp
> +}
2d8136e66e6b76afe10210e057b1d2aa0b196ade

2023-12-07 19:22 UTC, NikitaKonturov commented on laboratory-task-6/Laba6.cpp
> +}
2d8136e66e6b76afe10210e057b1d2aa0b196ade

2023-12-07 19:22 UTC, NikitaKonturov commented on laboratory-task-6/Laba6.cpp
> +template<typename TypeArr> // temlate for int, double,char
2d8136e66e6b76afe10210e057b1d2aa0b196ade

2023-12-07 19:22 UTC, NikitaKonturov commented on laboratory-task-6/Laba6.cpp
> +size_t BinareSearch(TypeArr* arr, size_t lenArr, TypeArr ell) {
2d8136e66e6b76afe10210e057b1d2aa0b196ade

2023-12-07 19:23 UTC, NikitaKonturov commented on laboratory-task-6/Laba6.cpp
> +        }
2d8136e66e6b76afe10210e057b1d2aa0b196ade

2023-12-07 19:23 UTC, NikitaKonturov commented on laboratory-task-6/Laba6.cpp
> +    }
2d8136e66e6b76afe10210e057b1d2aa0b196ade

2023-12-07 23:52 UTC, NikitaKonturov commented on laboratory-task-6/Laba6.cpp
> +    if (file.eof()) throw std::exception("File is epmty");
переработал получше 01f76397fe8e8b8ef13d7b4bed736b970b238e7f

2023-12-08 00:02 UTC, NikitaKonturov commented on laboratory-task-6/Laba6.cpp
> +    }
переработал 01f76397fe8e8b8ef13d7b4bed736b970b238e7f

2023-12-08 00:02 UTC, NikitaKonturov commented on laboratory-task-6/Laba6.cpp
> +}
01f76397fe8e8b8ef13d7b4bed736b970b238e7f

2023-12-08 00:13 UTC, NikitaKonturov commented on laboratory-task-6/Laba6.cpp
> +}
d575c27da00371d5a5f097d766ba10882fcde624

2024-01-06 19:13 UTC, AlexandrOsiptsov approved these changes
Кирилл сказал, что можно апрувить. Поэтому получай

2024-06-17 16:21 UTC, AlexandrOsiptsov approved these changes
Финальный авто-апрув

2024-06-17 16:40 UTC, merged