Добавил практическое задание №1
Programming-Classrooms/practicalworks-NikitaKonturov pull request #12
Opened 2023-11-29 19:33 UTC by NikitaKonturov

## Pull Request практической работы №1

### Условие практической работы

Программа должна перезаписывать сама себя же из .cpp в .txt 

### Вопросы по условию

2023-11-30 20:58 UTC, AlexandrOsiptsov requested changes
Шуруй работать

2023-11-30 20:58 UTC, AlexandrOsiptsov commented on practicalWorks/WorkWithFies.cpp
> +int checkFile(std::ifstream &file){
Зачем возвращаемое значение?

2023-11-30 20:58 UTC, AlexandrOsiptsov commented on practicalWorks/WorkWithFies.cpp
> +int copyFiles(std::ifstream &file, std::ofstream &newFile){
Аналогично

2023-11-30 20:58 UTC, AlexandrOsiptsov commented on practicalWorks/WorkWithFies.cpp
> +    std::ifstream file ("/home/nikita/Desktop/FolderByWorcsk/WorkWithFies.cpp");
Перед открытием файла, его директорию обычно сохраняют в константную переменную

2023-11-30 20:58 UTC, AlexandrOsiptsov commented on practicalWorks/WorkWithFies.cpp
> +    }catch(const char* error){
Мы используем класс `exception`.
Сообщения об ошибках выводятся в `std::cerr`

2023-11-30 20:58 UTC, AlexandrOsiptsov commented on practicalWorks/WorkWithFies.cpp
> +    std::ofstream newFile("WorckWithFiles.txt");
Работа на английском будет Work, а не Worck

2023-12-01 18:01 UTC, NikitaKonturov commented on practicalWorks/WorkWithFies.cpp
> +int checkFile(std::ifstream &file){
поменял на void 223e2759cfd59bda0039a40cc0a498664d5c1a96

2023-12-01 18:01 UTC, NikitaKonturov commented on practicalWorks/WorkWithFies.cpp
> +int copyFiles(std::ifstream &file, std::ofstream &newFile){
223e2759cfd59bda0039a40cc0a498664d5c1a96

2023-12-01 18:05 UTC, NikitaKonturov commented on practicalWorks/WorkWithFies.cpp
> +    std::ofstream newFile("WorckWithFiles.txt");
поменял 223e2759cfd59bda0039a40cc0a498664d5c1a96

2023-12-01 18:07 UTC, NikitaKonturov commented on practicalWorks/WorkWithFies.cpp
> +    std::ifstream file ("/home/nikita/Desktop/FolderByWorcsk/WorkWithFies.cpp");
сохранил e04e4a94734b024c5d1459a737398aa7dc8b0eb8

2023-12-01 19:24 UTC, AlexandrOsiptsov requested changes
Поменяй название папки на `practical-works`

2023-12-01 19:37 UTC, AlexandrOsiptsov requested changes
Поменяй название папки на practical-works

2023-12-02 19:48 UTC, AlexandrOsiptsov requested changes
А старую папку чего не удалил?

2023-12-02 19:57 UTC, AlexandrOsiptsov approved these changes

2023-12-02 19:59 UTC, merged