Лабораторную работу №8
Programming-Classrooms/practicalworks-NikitaKonturov pull request #15
Opened 2023-12-05 17:52 UTC by NikitaKonturov

## Pull Request лабораторной работы №X

### Условие лабраторной работы

< Словом, входящим в состав строки, назовём непрерывную
последовательность символов, ограниченную символами–разделителями,
началом и концом строки. Символы, относящиеся к разделителям, определяет
пользователь, если иное не сказано в условии задачи. Если решить задачу
невозможно, программа должна выдать соответствующее сообщение.

Строка состоит из слов, разделённых знаками препинания. За один
просмотр символов строки найти все слова, представляющие собой числа
Армстронга и занести их в новую строку. Слова в новой строке должны
разделяться ровно одним пробелом. >

### Вопросы по условию

2024-01-12 10:19 UTC, AlexandrOsiptsov requested changes
Заверните две

2024-01-12 10:19 UTC, AlexandrOsiptsov commented on laboratory-task-8/seekNumberInLine.cpp
> +#include "seekNumbersInLine.hpp"
Пробелы лень ставить?

2024-01-12 10:19 UTC, AlexandrOsiptsov commented on laboratory-task-8/seekNumberInLine.cpp
> +            num = static_cast<int32_t>(word[i]) - '0';
Ненужное преобразования. Подумай

2024-01-12 15:49 UTC, NikitaKonturov commented on laboratory-task-8/seekNumberInLine.cpp
> +#include "seekNumbersInLine.hpp"
Поставил 09ef2aa21681c1988089d59ccfcd6bc3410e2d9f

2024-01-12 15:49 UTC, NikitaKonturov commented on laboratory-task-8/seekNumberInLine.cpp
> +            num = static_cast<int32_t>(word[i]) - '0';
Подумал 09ef2aa21681c1988089d59ccfcd6bc3410e2d9f

2024-06-17 16:21 UTC, AlexandrOsiptsov approved these changes
Финальный авто-апрув

2024-06-17 16:40 UTC, merged