Лабораторная работа №9
Programming-Classrooms/practicalworks-NikitaKonturov pull request #17
Opened 2023-12-16 22:50 UTC by NikitaKonturov

## Pull Request лабораторной работы №9

### Условие лабраторной работы

4. Строки текстового файла input.txt состоят из слов, разделенных одним  или несколькими пробелами.
Перед первым, а также после последнего слова  строки пробелы могут отсутствовать.
Требуется определить строки,  содержащие максимальное количество слов.
Если таких строк несколько,  найти первые 10.
Результат вывести на консоль в форме, удобной для чтения.

### Вопросы по условию

2024-01-12 10:35 UTC, AlexandrOsiptsov requested changes

2024-01-12 10:35 UTC, AlexandrOsiptsov commented on laboratory-task-9/laboratory-task-9-main/main.cpp
> +        std::cout << linesWithMaxNumberOfWords << std::endl;
Логического разделения бы

2024-01-12 10:35 UTC, AlexandrOsiptsov commented on laboratory-task-9/laboratory-task-9-main/workWithFiles.cpp
> +#include <regex>
Сначала обычно пишут подключения системных модулей, а потом уже пользовательских. Не мешай

2024-01-12 10:35 UTC, AlexandrOsiptsov commented on laboratory-task-9/laboratory-task-9-main/workWithFiles.cpp
> +std::string seekLinnesWithMaxNumberWords(std::string textWithAllLines)
линнес

2024-01-12 10:35 UTC, AlexandrOsiptsov commented on laboratory-task-9/laboratory-task-9-main/workWithFiles.cpp
> +    return linesWithMaxWords;
Что по логическому разделению. У тебя функция - месиво

2024-01-12 17:29 UTC, NikitaKonturov commented on laboratory-task-9/laboratory-task-9-main/main.cpp
> +        std::cout << linesWithMaxNumberOfWords << std::endl;
962f67116e6619d74f022e84d97ff1e5156ecce2

2024-01-12 17:29 UTC, NikitaKonturov commented on laboratory-task-9/laboratory-task-9-main/workWithFiles.cpp
> +#include <regex>
962f67116e6619d74f022e84d97ff1e5156ecce2

2024-01-12 17:30 UTC, NikitaKonturov commented on laboratory-task-9/laboratory-task-9-main/workWithFiles.cpp
> +std::string seekLinnesWithMaxNumberWords(std::string textWithAllLines)
Это отсылка к Linux 962f67116e6619d74f022e84d97ff1e5156ecce2

2024-01-12 17:30 UTC, NikitaKonturov commented on laboratory-task-9/laboratory-task-9-main/workWithFiles.cpp
> +    return linesWithMaxWords;
962f67116e6619d74f022e84d97ff1e5156ecce2

2024-06-17 14:28 UTC, AlexandrOsiptsov approved these changes
Финальный авто-апрув

2024-06-17 14:28 UTC, merged