Commited laba1
Programming-Classrooms/practicalworks-NikitaKonturov pull request #2
Opened 2023-11-26 20:31 UTC by NikitaKonturov

2023-11-28 07:22 UTC, AlexandrOsiptsov requested changes
Просмотри комментарии и исправь кодировку вывода

2023-11-28 07:22 UTC, AlexandrOsiptsov commented on laboratory-task-1/LabNum1.cpp
> +			*/
Не должно быть закомменченного кода

2023-11-28 07:22 UTC, AlexandrOsiptsov commented on laboratory-task-1/LabNum1.cpp
> +	catch (...) {
catch должен отлавливать конкретные исключения, и выводить их ошибку. Реализуй через класс `exception`

2023-11-28 17:46 UTC, NikitaKonturov commented on laboratory-task-1/LabNum1.cpp
> +			*/
Убрал 3ce43dd286df3b49e29b5b0ab29e56e18b0781c2

2023-11-28 17:46 UTC, NikitaKonturov commented on laboratory-task-1/LabNum1.cpp
> +	catch (...) {
Переписал 3ce43dd286df3b49e29b5b0ab29e56e18b0781c2

2024-01-06 18:12 UTC, AlexandrOsiptsov requested changes

2024-01-06 18:12 UTC, AlexandrOsiptsov commented on laboratory-task-1/main.cpp
> +			i++;
какого

2024-01-06 18:12 UTC, AlexandrOsiptsov commented on laboratory-task-1/main.cpp
> +}
Пустая строка

2024-01-06 18:24 UTC, NikitaKonturov commented on laboratory-task-1/main.cpp
> +			i++;
89d15b7f9c4649b40f3fb2ea5eb44376c156b2de

2024-01-06 18:24 UTC, NikitaKonturov commented on laboratory-task-1/main.cpp
> +}
89d15b7f9c4649b40f3fb2ea5eb44376c156b2de

2024-06-17 16:42 UTC, merged