Laba4
Programming-Classrooms/practicalworks-NikitaKonturov pull request #8
Opened 2023-11-26 21:13 UTC by NikitaKonturov

2023-11-28 08:38 UTC, AlexandrOsiptsov requested changes
Ты не приложил .h к PR. + просмотри комменты

2023-11-28 08:38 UTC, AlexandrOsiptsov commented on laboratory-task-4/Laba4.cpp
> +	SetConsoleOutputCP(1225);
Вот это правильно, респект, так всегда и делайте. Диалог резолви сам

2023-11-28 08:38 UTC, AlexandrOsiptsov commented on laboratory-task-4/Laba4.cpp
> +#include "WorckWithMatrix.h"
Где файл???

2023-11-28 08:38 UTC, AlexandrOsiptsov commented on laboratory-task-4/Laba4.cpp
> +	MatrixDefine(matrix, rows, colums);
Почему функция в PascalCase а не camelCase?

2023-11-28 08:38 UTC, AlexandrOsiptsov commented on laboratory-task-4/Laba4.cpp
> +	SortLines(matrix, rows, colums);
Почему функция в PascalCase а не camelCase?

2023-11-28 08:38 UTC, AlexandrOsiptsov commented on laboratory-task-4/Laba4.cpp
> +	delete[] matrix;
Последняя строка должна быть в функции delMatrix(). Название ф-ции так себе. Лучше что-то типа "mtrxMemClear"

2023-11-28 08:38 UTC, AlexandrOsiptsov commented on laboratory-task-4/Laba4.cpp
> +}
Лишние пустые строки, а в конце пустой строки нет.
В любом коде в конце файла принято оставлять одну пустую строку

2023-11-28 08:39 UTC, AlexandrOsiptsov commented on laboratory-task-4/Laba4.cpp
> +#include "WorckWithMatrix.h"
Слово "работа", кстати, пишется как "work", а не "worck"

2023-11-28 18:29 UTC, NikitaKonturov commented on laboratory-task-4/Laba4.cpp
> +	MatrixDefine(matrix, rows, colums);
Исправил be22f2ea1dfd5119d8c533a1fa1fa1eb1a69d82a

2023-11-28 18:30 UTC, NikitaKonturov commented on laboratory-task-4/Laba4.cpp
> +	SortLines(matrix, rows, colums);
Исправил be22f2ea1dfd5119d8c533a1fa1fa1eb1a69d82a

2023-11-28 18:31 UTC, NikitaKonturov commented on laboratory-task-4/Laba4.cpp
> +#include "WorckWithMatrix.h"
Вот be22f2ea1dfd5119d8c533a1fa1fa1eb1a69d82a

2024-01-06 18:51 UTC, Voio77 requested changes
Все знаешь!

2024-01-06 18:57 UTC, Voio77 approved these changes
Good Luck!

2024-01-06 19:01 UTC, AlexandrOsiptsov approved these changes

2024-01-06 19:02 UTC, merged