Лабораторная работа №5
Programming-Classrooms/practicalworks-NikitaKonturov pull request #9
Opened 2023-11-26 21:17 UTC by NikitaKonturov

2023-12-05 08:22 UTC, AnnaSatolina requested changes
Разберись , пожалуйста, с кодировкой

2023-12-05 08:22 UTC, AnnaSatolina commented on laboratory-task-5/Laba5.cpp
> +double difference(double x) { // ������ ��������������� �������
кодировка

2023-12-05 18:02 UTC, NikitaKonturov commented on laboratory-task-5/Laba5.cpp
> +double difference(double x) { // ������ ��������������� �������
исправил 943900611d377830c7cec33948451a87fe77057b

2024-01-06 18:15 UTC, AlexandrOsiptsov requested changes

2024-01-06 18:15 UTC, AlexandrOsiptsov commented on laboratory-task-5/main.cpp
> + return 0;
Отступы

2024-01-06 18:28 UTC, NikitaKonturov commented on laboratory-task-5/main.cpp
> + return 0;
155eb91d20fa4bb8b33276196ffdf92846beb7cb

2024-06-17 16:21 UTC, AlexandrOsiptsov approved these changes
Финальный авто-апрув

2024-06-17 16:42 UTC, merged